version: '3.8'

services:
    users:
        container_name: users
        build:
            context: .
            dockerfile: apps/users/Dockerfile
        env_file: .env
        ports:
            - 3000:3000
            - 9229:9229 # For debugger
        networks:
            - app-network
        volumes:
            - ./apps/users/src:/app/apps/users/src
            - ./logs:/var/logs/
        depends_on:
            - db
    db:
        image: mongo:latest
        container_name: db
        restart: unless-stopped
        environment:
            - MONGO_INITDB_ROOT_USERNAME=guest
            - MONGO_INITDB_ROOT_PASSWORD=guest
        command: mongod --port 27017
        ports:
            - 27017:27017
        volumes:
            - dbdata:/data/db
        networks:
            - app-network
networks:
    app-network:
volumes:
    dbdata:
